module.exports = {
  UPDATE_INTERVAL_MS: 2000,
  DEFAULT_SPEED_KMH: 30,
  SPEED_VARIATION: 10,
  OCCUPANCY_LEVELS: ["Low", "Medium", "High", "Full"],
  DELAY_CHANCE: 0.15,
  MAX_DELAY_MINUTES: 5,
  NEARBY_THRESHOLD_METERS: 100,

  // Nagpur ke real major stops (approximate coordinates)
  STOPS: {
    sitabuldi: { id: "sitabuldi", name: "Sitabuldi Interchange", lat: 21.1461, lng: 79.0849 },
    civil_lines: { id: "civil_lines", name: "Civil Lines", lat: 21.155, lng: 79.08 },
    dharampeth: { id: "dharampeth", name: "Dharampeth Square", lat: 21.142, lng: 79.064 },
    sadar: { id: "sadar", name: "Sadar", lat: 21.16, lng: 79.075 },
    congress_nagar: { id: "congress_nagar", name: "Congress Nagar", lat: 21.148, lng: 79.068 },
    ramdaspeth: { id: "ramdaspeth", name: "Ramdaspeth", lat: 21.138, lng: 79.078 },
    gandhibagh: { id: "gandhibagh", name: "Gandhibagh", lat: 21.155, lng: 79.105 },
    itwari: { id: "itwari", name: "Itwari", lat: 21.158, lng: 79.108 },
    mankapur: { id: "mankapur", name: "Mankapur", lat: 21.175, lng: 79.115 },
    kamptee_bus_stand: { id: "kamptee_bus_stand", name: "Kamptee Bus Stand", lat: 21.2, lng: 79.2 },
    ajni: { id: "ajni", name: "Ajni Square", lat: 21.125, lng: 79.07 },
    mihan: { id: "mihan", name: "MIHAN (AIIMS)", lat: 21.09, lng: 79.045 },
    manish_nagar: { id: "manish_nagar", name: "Manish Nagar", lat: 21.115, lng: 79.055 },
    hingna: { id: "hingna", name: "Hingna", lat: 21.11, lng: 78.99 },
    pardi: { id: "pardi", name: "Pardi", lat: 21.165, lng: 79.13 },
    medical_square: { id: "medical_square", name: "Medical Square", lat: 21.13, lng: 79.09 },
    vnit: { id: "vnit", name: "VNIT Square", lat: 21.125, lng: 79.05 },
    futala_lake: { id: "futala_lake", name: "Futala Lake", lat: 21.155, lng: 79.045 },
    variety_square: { id: "variety_square", name: "Variety Square", lat: 21.147, lng: 79.081 },
    wathoda: { id: "wathoda", name: "Wathoda", lat: 21.165, lng: 79.14 },
    isasani: { id: "isasani", name: "Isasani (Krushna Nagar)", lat: 21.08, lng: 79.2 },
    ycce: { id: "ycce", name: "Y.C.C.E. College", lat: 21.12, lng: 79.115 },
    defence_gate: { id: "defence_gate", name: "Defence Gate No. 3", lat: 21.22, lng: 79.2 },
    nara: { id: "nara", name: "Nara", lat: 21.05, lng: 78.9 },
    narsala: { id: "narsala", name: "Narsala", lat: 21.06, lng: 79.03 },
    panchasheel_chowk: { id: "panchasheel_chowk", name: "Panchasheel Chowk", lat: 21.14, lng: 79.085 },
  },

  // Real Aapli Bus Nagpur route numbers, mapped to actual stop sequences
  ROUTES: [
    { id: "route_01", name: "Route 1 (Pardi)", stopIds: ["sitabuldi", "variety_square", "ramdaspeth", "ajni", "medical_square", "pardi"] },
    { id: "route_20", name: "Route 20 (Kamptee Bus Stand)", stopIds: ["sitabuldi", "civil_lines", "sadar", "mankapur", "kamptee_bus_stand"] },
    { id: "route_32", name: "Route 32 (Isasani)", stopIds: ["sitabuldi", "gandhibagh", "itwari", "wathoda", "isasani"] },
    { id: "route_35", name: "Route 35 (Pardi via YCCE)", stopIds: ["ycce", "vnit", "medical_square", "ajni", "pardi"] },
    { id: "route_40", name: "Route 40 (Defence Gate No. 3)", stopIds: ["sitabuldi", "civil_lines", "mankapur", "kamptee_bus_stand", "defence_gate"] },
    { id: "route_48", name: "Route 48 (Nara)", stopIds: ["sitabuldi", "dharampeth", "vnit", "hingna", "nara"] },
    { id: "route_52", name: "Route 52 (Narsala)", stopIds: ["sitabuldi", "ajni", "medical_square", "narsala"] },
    { id: "route_07stl", name: "Route 07STL (Panchasheel Chowk)", stopIds: ["congress_nagar", "ramdaspeth", "panchasheel_chowk"] },
    { id: "route_287", name: "Route 287 (MIHAN – Sitabuldi)", stopIds: ["mihan", "manish_nagar", "vnit", "ajni", "medical_square", "sitabuldi"] },
    { id: "route_10", name: "Route 10 (Futala Loop)", stopIds: ["sitabuldi", "civil_lines", "futala_lake", "dharampeth", "congress_nagar"] },
  ],

  // 10 buses, ek-ek route assign
  BUSES: [
    { busId: "bus_001", routeId: "route_01" },
    { busId: "bus_002", routeId: "route_20" },
    { busId: "bus_003", routeId: "route_32" },
    { busId: "bus_004", routeId: "route_35" },
    { busId: "bus_005", routeId: "route_40" },
    { busId: "bus_006", routeId: "route_48" },
    { busId: "bus_007", routeId: "route_52" },
    { busId: "bus_008", routeId: "route_07stl" },
    { busId: "bus_009", routeId: "route_287" },
    { busId: "bus_010", routeId: "route_10" },
  ],
};